services:
  event-service:
    container_name: event-service
    build: .
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - event-service:/app
    ports:
      - "7003:8000"
    depends_on:
      - event-postgres

  event-postgres:
    image: postgres:15
    container_name: event-postgres
    restart: always
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - event-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  event-service:
  event-db:
